
export const CMP_PAGE = "CMP_PAGE";
export const CMP_PAGE_HEADER = "CMP_PAGE_HEADER";
export const CMP_PAGE_HEADER_TITLE = "CMP_PAGE_HEADER_TITLE";
export const CMP_PAGE_CONTENT = "CMP_PAGE_CONTENT";
export const CMP_SEARCH_FILTER = "CMP_SEARCH_FILTER";

export const CMP_LIST = "CMP_LIST";

export const CMP_LIST_VIEW = "CMP_LIST_VIEW";
export const CMP_LIST_VIEW_ENTITY_LABELED_STRING = "CMP_LIST_VIEW_ENTITY_LABELED_STRING";
export const CMP_LIST_VIEW_ENTITY_LABELED_CHECKBOX = "CMP_LIST_VIEW_ENTITY_LABELED_CHECKBOX";
export const CMP_LIST_VIEW_ENTITY_CARD = "CMP_LIST_VIEW_ENTITY_CARD";
export const CMP_LIST_VIEW_ENTITY_BUTTON = "CMP_LIST_VIEW_ENTITY_BUTTON";

export const CMP_CUSTOM_HTML = "CMP_CUSTOM_HTML";

export const CMP_LIST_EDIT = "CMP_LIST_EDIT";
export const CMP_LIST_EDIT_ENTITY_HIDDEN = "CMP_LIST_EDIT_ENTITY_HIDDEN";
export const CMP_LIST_EDIT_ENTITY_BUTTON = "CMP_LIST_EDIT_ENTITY_BUTTON";
export const CMP_LIST_EDIT_ENTITY_LABELED = "CMP_LIST_EDIT_ENTITY_LABELED";
export const CMP_LIST_EDIT_ENTITY_LABELED_DATE = "CMP_LIST_EDIT_ENTITY_LABELED_DATE";
export const CMP_LIST_EDIT_ENTITY_LABELED_CHECKBOX = "CMP_LIST_EDIT_ENTITY_LABELED_CHECKBOX";
export const CMP_LIST_EDIT_ENTITY_LABELED_SELECT = "CMP_LIST_EDIT_ENTITY_LABELED_SELECT";
export const CMP_LIST_EDIT_ENTITY_LABELED_FILTERING_SELECT = "CMP_LIST_EDIT_ENTITY_LABELED_FILTERING_SELECT";
export const CMP_LIST_EDIT_ENTITY_LABELED_STRING = "CMP_LIST_EDIT_ENTITY_LABELED_STRING";
export const CMP_LIST_EDIT_ENTITY_LABELED_NUMBER = "CMP_LIST_EDIT_ENTITY_LABELED_NUMBER";
export const CMP_LIST_EDIT_ENTITY_LABELED_HIDDEN = "CMP_LIST_EDIT_ENTITY_LABELED_HIDDEN";
export const CMP_LIST_EDIT_ENTITY_LABELED_DISABLED_STRING = "CMP_LIST_EDIT_ENTITY_LABELED_DISABLED_STRING";

export const CMP_BUTTON = "CMP_BUTTON";

export const ACT_GET_BY_ID = "ACT_GET_BY_ID";
export const ACT_GO_TO = "ACT_GO_TO";
export const ACT_FORM_SUBMIT = "ACT_FORM_SUBMIT";
export const ACT_DELETE = "ACT_DELETE";

export const TYPE_STRING = "string";
export const TYPE_NUMBER = "number";
export const TYPE_BUTTON = "button";
export const TYPE_BUTTON_SUBMIT = "button-submit";